---
title: "Simulacion LASA"
author: "Jose Pablo Gómez Mata"
date: "3/23/2022"
output: html_document
editor_options: 
  chunk_output_type: console
---

# Lo que se espera encontrar

```{r}
N <- 3 # numero de patrones que quieran
r <- 4 # cantidad de repeticiones por patron



sigma<- 0.002 

prom1 <- 0.13
prom2 <- 0.35
prom3 <- 0.60
prom4 <- 0.90
prom5 <- 1.25

senial <- c()

patron <- factor(rep(1:N,each=r))

for (i in 1:length(patron)) {

  if(patron[i] == 1){
    
    senial[i] =  abs(rnorm(n=r, mean= prom1, sd=sqrt(sigma)))
    
  }else if(patron[i] == 2){
    
    senial[i] = abs(rnorm(n=r, mean= prom2, sd=sqrt(sigma)))
    
  }else if(patron[i] == 3){
    
    senial[i] = abs(rnorm(n=r, mean= prom3, sd=sqrt(sigma)))
    
  # }else if(patron[i] == 4){
  #  
  #   senial[i] = abs(rnorm(n=r, mean= prom4, sd=sqrt(sigma)))
     
  # }else if(patron[i] == 5){
  #   
  #   senial[i] = abs(rnorm(n=r, mean= prom5, sd=sqrt(sigma)))
  #   
  }
  
} 


senial <- as.numeric(senial)
base <- data.frame(cbind(patron,senial))

plot(base$patron,base$senial)

# library(ggplot2)
# 
# ggplot(base, aes(patron,senial)) + 
#   geom_point() +
#   geom_smooth(method = "lm") 
# ------------------------------------------------------------------- REPRODUCIBILIDAD Y REPETIBILIDAD ----------------------------------------------------------------------------
# R&R:
N <- 1 # numero de patrones que quieran
r <- 12 # cantidad de repeticiones por patron

sigma<- 0.000000000000001 

prom1 <- 0.13

senial <- c()

patron <- factor(rep(1:N,each=r))

for (i in 1:length(patron)) {

  if(patron[i] == 1){
    
    senial[i] =  abs(rnorm(n=r, mean= prom1, sd=sqrt(sigma)))
    
  }
  
}

senial <- as.numeric(senial)
analistas <- factor(rep(c("lucia","adrian"),each = 2, times = 3))
repe <- rep(c(1,2),6)
ue <- rep(1:3,each = 4)
base <- data.frame(cbind(patron,senial,analistas,repe,ue))

base$ue <- factor(base$ue)
base$repe <- factor(base$repe)
base$analistas <- factor(base$analistas)
levels(base$analistas) = c("lucia","adrian")
str(base)
# visualizacion:
library(lattice)
bwplot(senial~analistas|ue,layout=c(3,1),ylab = "respuesta",data = base)
dotplot(senial~analistas|ue,xlab="Operadores",layout=c(3,1),data=base)
xyplot(senial~ue,groups = analistas, type = c("p", "a"),pch = 18,  ylab = "Respuesta", base)
plot(tapply(base$senial,base$ue,mean),type = "l",xlab = "pieza",ylab = "respuesta promedio")
```

```{r}
table(base$analistas,base$repe)
```

# si aumentamos el tamaño de muestra (numero de UE)
```{r}
N <- 1 # numero de patrones que quieran
r <- 20 # cantidad de repeticiones por patron

sigma<- 0.001 

prom1 <- 0.13

senial <- c()

patron <- factor(rep(1:N,each=r))

for (i in 1:length(patron)) {

  if(patron[i] == 1){
    
    senial[i] =  abs(rnorm(n=r, mean= prom1, sd=sqrt(sigma)))
    
  }
  
}

senial <- as.numeric(senial)
analistas <- factor(rep(c("lucia","adrian"),each = 2, times = 5))
repe <- rep(c(1,2),10)
ue <- rep(1:5,each = 4)
base <- data.frame(cbind(patron,senial,analistas,repe,ue))

base$ue <- factor(base$ue)
base$repe <- factor(base$repe)
base$analistas <- factor(base$analistas)
levels(base$analistas) = c("lucia","adrian")
str(base)
# visualizacion:
library(lattice)
bwplot(senial~analistas|ue,layout=c(5,1),ylab = "respuesta",data = base)
dotplot(senial~analistas|ue,xlab="Operadores",layout=c(5,1),data=base)
xyplot(senial~ue,groups = analistas, type = c("p", "a"),pch = 18,  ylab = "Respuesta", base)
plot(tapply(base$senial,base$ue,mean),type = "l",xlab = "pieza",ylab = "respuesta promedio")
```

```{r}
table(base$ue,base$analistas)
```

# si aumentamos el tamaño de muestra (numero de rep)
```{r}
N <- 1 # numero de patrones que quieran
r <- 24 # cantidad de repeticiones por patron

sigma<- 0.00001 

prom1 <- 0.13

senial <- c()

patron <- factor(rep(1:N,each=r))

for (i in 1:length(patron)) {

  if(patron[i] == 1){
    
    senial[i] =  abs(rnorm(n=r, mean= prom1, sd=sqrt(sigma)))
    
  }
  
}

senial <- as.numeric(senial)
analistas <- factor(rep(c("lucia","adrian"),each = 3, times = 4))
repe <- rep(c(1:3),8)
ue <- rep(1:4,each = 6)
base <- data.frame(cbind(patron,senial,analistas,repe,ue))

base$ue <- factor(base$ue)
base$repe <- factor(base$repe)
base$analistas <- factor(base$analistas)
levels(base$analistas) = c("lucia","adrian")
str(base)
# visualizacion:
library(lattice)
bwplot(senial~analistas|ue,layout=c(4,1),ylab = "respuesta",data = base)
dotplot(senial~analistas|ue,xlab="Operadores",layout=c(4,1),data=base)
xyplot(senial~ue,groups = analistas, type = c("p", "a"),pch = 18,  ylab = "Respuesta", base)
plot(tapply(base$senial,base$ue,mean),type = "l",xlab = "pieza",ylab = "respuesta promedio")
```

```{r}
table(base$ue,base$analistas)
```

# Lo que no se espera encontrar

```{r}
N <- 5 # numero de patrones que quieran
r <- 3 # cantidad de repeticiones por patron



# sigma<- 0.002 

prom1 <- 0.13
prom2 <- 0.35
prom3 <- 0.60
prom4 <- 0.95
prom5 <- 1.25

senial <- c()

patron <- factor(rep(1:N,each=r))

for (i in 1:length(patron)) {

  if(patron[i] == 1){
    
    senial[i] =  abs(rnorm(n=r, mean= prom1, sd=sqrt(0.0002)))
    
  }else if(patron[i] == 2){
    
    senial[i] = abs(rnorm(n=r, mean= prom2, sd=sqrt(0.002)))
    
  }else if(patron[i] == 3){
    
    senial[i] = abs(rnorm(n=r, mean= prom3, sd=sqrt(0.01)))
    
  }else if(patron[i] == 4){
   
    senial[i] = abs(rnorm(n=r, mean= prom4, sd=sqrt(0.02)))
     
  }else if(patron[i] == 5){
    
    senial[i] = abs(rnorm(n=r, mean= prom5, sd=sqrt(0.1)))
    
  }
  
} 
senial <- as.numeric(senial)
base <- data.frame(cbind(patron,senial))

plot(base$patron,base$senial)

# library(ggplot2)
# 
# ggplot(base, aes(patron,senial)) + 
#   geom_point() +
#   geom_smooth(method = "lm") 
```




```{r}
"HOLA"
```













